server:
  port: 80
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: dev

  data:
    elasticsearch:
      cluster-nodes: xxxxxxxx:9300
      cluster-name: my-application

  redis:
    host: localhost
    password: xxxxxxxx
    database: 1
    port: 6379
    timeout: 500ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0

  datasource:
    url: jdbc:mysql://xxxxxxxx:3306/life_with_notes?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: xxxxxxxx
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: -1
      filters: stat,wall,log4j
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8

  mvc:
    favicon:
      enabled: false

  servlet:
    multipart:
      max-file-size: 10Mb
      max-request-size: 100Mb

druidUsername: xxxxxxxx
druidPassword: xxxxxxxx

aliyun:
  accessKeyId: xxxxxxxxxxxxxxxx
  secret: xxxxxxxxxxxxxxxx

tencent:
  cloud:
    appid: xxxxxxxx
    appkey: xxxxxxxxxxxxxxxx

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count

#log config
logging:
  config: classpath:log4j2.xml